using AgileSync.Shared.Models;
using FluentAssertions;

namespace AgileSync.Shared.Tests;

/// <summary>Concrete subclass used to test the abstract BaseEntity.</summary>
file class TestEntity : BaseEntity { }

public class BaseEntityTests
{
    [Fact]
    public void Id_IsAutoGenerated_AndNotEmpty()
    {
        var entity = new TestEntity();
        entity.Id.Should().NotBeNullOrWhiteSpace();
    }

    [Fact]
    public void Id_IsUnique_AcrossInstances()
    {
        var a = new TestEntity();
        var b = new TestEntity();
        a.Id.Should().NotBe(b.Id);
    }

    [Fact]
    public void CreatedAt_DefaultsToUtcNow()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var entity = new TestEntity();
        var after = DateTime.UtcNow.AddSeconds(1);

        entity.CreatedAt.Should().BeAfter(before).And.BeBefore(after);
    }

    [Fact]
    public void UpdatedAt_DefaultsToUtcNow()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var entity = new TestEntity();
        var after = DateTime.UtcNow.AddSeconds(1);

        entity.UpdatedAt.Should().BeAfter(before).And.BeBefore(after);
    }

    [Fact]
    public void TenantId_DefaultsToNull()
    {
        var entity = new TestEntity();
        entity.TenantId.Should().BeNull();
    }

    [Fact]
    public void TenantId_CanBeSet()
    {
        var entity = new TestEntity { TenantId = "abc123" };
        entity.TenantId.Should().Be("abc123");
    }
}
